version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lunchrunner
      POSTGRES_USER: lunchrunner
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lunchrunner"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://lunchrunner:supersecretpassword@db:5432/lunchrunner
      CORS_ORIGIN: http://localhost:3000
      CLERK_PUBLISHABLE_KEY: pk_test_your_publishable_key
      CLERK_SECRET_KEY: sk_test_your_secret_key
      CLERK_ISSUER_URL: https://your-app.clerk.accounts.dev
      CLERK_JWT_AUDIENCE: http://localhost:3000
      CLERK_JWT_TEMPLATE: backend
      CLERK_API_BASE_URL: https://api.clerk.com
      CLERK_ADMIN_ROLE: admin
      CLERK_SIGN_IN_URL: https://your-app.clerk.accounts.dev/sign-in
      CLERK_SIGN_UP_URL: https://your-app.clerk.accounts.dev/sign-up
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  db_data:
