server:
  port: ${PORT:3000}
  forward-headers-strategy: native
spring:
  application:
    name: lunchrunner-backend
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    default-property-inclusion: non_null
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
